steps:
  # Check if the Artifact Registry repository exists
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      - "-c"
      - |
        if gcloud artifacts repositories describe ${_SERVICE_NAME} --location=us-west1 --project=portfolio-400613 >/dev/null 2>&1; then
          echo "Repository exists."
        else
          echo "Repository does not exist. Creating..."
          gcloud artifacts repositories create ${_SERVICE_NAME} --repository-format=docker \
            --location=us-west1 --project=portfolio-400613
        fi
  # Build and push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west1-docker.pkg.dev/portfolio-400613/${_SERVICE_NAME}/${_SERVICE_NAME}:$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west1-docker.pkg.dev/portfolio-400613/${_SERVICE_NAME}/${_SERVICE_NAME}:$SHORT_SHA",
      ]
  # Deploy the image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--region=us-west1",
        "--platform=managed",
        "--image=us-west1-docker.pkg.dev/portfolio-400613/${_SERVICE_NAME}/${_SERVICE_NAME}:$SHORT_SHA",
        "--allow-unauthenticated",
      ]
images:
  - "us-west1-docker.pkg.dev/portfolio-400613/${_SERVICE_NAME}/${_SERVICE_NAME}:$SHORT_SHA"
